### ISSUE TITLE
[OFFER] WEbstorm

### ISSUE THREAD

**Issue by artel1992** [abeade/figma-import-plugin#9]
You have an excellent plugin, it would be great if you implemented it in WebStorm.

**Comment by abeade** [comment]
Hi @artel1992 

Sorry for the late response.

The plugin was created keeping in mind the needs of Android; As an Android developer, this was a need I found for myself and decided to create the plugin and make it public.

Since the plugin is coupled to Android density resources (`ldpi`, `mdpi`...), I'm not sure how it can fit with the structure of web resources.

**Comment by abeade** [comment]
Thanks for the feedback! 😊
